### ISSUE TITLE
Automatic rounding of values makes timechart less usable

### ISSUE THREAD

**Issue by rbhtrifork** [humio/issues#53] opened 2018-10-31 11:58 UTC
### Case
We are uploading pressure data ~1kPa +-100Pa.
But when loaded in to a time chart everything above 1000Pa is rounded to 1kPa
Also when hovering above the chart to get exact value, this is rounded as well.

### Possible solutions
Make it possible to disable or change rounding of values 

### Details and images
Run on cloud.humio using Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Screenshot of dashboard widget**
![image](https://user-images.githubusercontent.com/19591639/47786292-9b056180-dd0b-11e8-8f14-d35060aa755e.png)

**Screenshot of search view**
![image](https://user-images.githubusercontent.com/19591639/47786168-34804380-dd0b-11e8-8069-dda9f60e7f61.png)

**Comment by pmech** [comment] 2018-10-31 12:54
Hi, and thanks for you report.

We recently Shift hover full precision. Try holding Shift down while hovering over the chart entries. Does that solve you problem?

**Comment by rbhtrifork** [comment] 2018-10-31 13:02
It solves the issue of reading the exact value at a point in time, but not
the issue of not being able to read the chart.

We have read-only dashboard without the ability to hover, so we only have
the chart widget itself to read the values from.
An example of a worst case scenario:
[image: image.png]
---------------------------------------------------------------------------------------------------------------------

Mvh/
Best regards

Rune Haugaard

**Comment by pmech** [comment] 2018-10-31 13:52
I get the issue now.

@anagrius Do you have a good solution to this. The problem is that the most of the values on the y-axis is just `1kpa` and you cannot really tell if that means 1000 or 1400.

**Comment by anagrius** [comment] 2019-02-10 13:19
Closing for now. We will address it when we implement new time charts.

**Closed by anagrius** 2019-02-10 13:19 UTC

**Comment by fyang13** [comment] 2023-03-24 21:50
With latest timechart and barchart, this issue still exist. Should this be reopened and new issue created?
