### ISSUE TITLE
Feature Request - Continue live query on scroll to top

### ISSUE THREAD

**Issue by Noloxs** [humio/issues#68] opened 2019-01-09 10:01 UTC
A really helpful addition would be if you could scroll to top to continue a live query.

So you would be able to run a live query.
Pause it to review the current data
Then simply scroll to top to continue the live view.

**Comment by mwl** [comment] 2019-01-09 10:12
I actually think that's by design. Think cases where the stream is so fast that the window will disappear out the bottom immediately when to move to the head of the stream, which would cause you to loose the "view".

Maybe @anagrius would give us some more insights?

**Comment by anagrius** [comment] 2019-01-09 10:14
@Noloxs Isn't that exactly what happens when you click "Resume Stream"?
Else I am misunderstanding what you want.

**Comment by Noloxs** [comment] 2019-01-09 10:45
Yes it is the same as when you hit the Resume stream.

It might be an issue the only I encounter because of how i use it.
For example.

- I would make a query to follow specific logs from a specific device as part of debugging.
- Then when I notice something of interest (or by mistake) scroll down to pause the stream and review the logs.
- I would then want to quickly resume the stream, and having to press the resume button every time, breaks my train of thought.

I know that I could just press the esc button to resume, but this also "at least at times" interrupts my train of thought
Also a lot of times, I simply don't notice that it is pause and afterwards find my self scrolling to top to resume.

In hindsight this should probably be taken as input and feedback, depicting an issue I encounter with my use, and asses if it should be written of as a user error or if other users find themselves with similar "issues"

**Comment by anagrius** [comment] 2019-02-10 12:00
I think I misunderstood your initial idea, about continuing on scroll to top. It is a good idea but it should be a user setting in that case. We will keep it in mind and close this for now. We are adding more user customisation on how search works and will address it at that time.

**Closed by anagrius** 2019-02-10 12:00 UTC
